apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura

spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: natan4dev/conversao-temperatura
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: '250Mi'
              cpu: '250m'
---
apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    app: conversao-temperatura
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 31000
  type: NodePort
